name: Update gist
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Update gist
        uses: maxam2017/productive-box@master
        env:
          GH_TOKEN: 7aaf1e1f3d177dd1feeae587f6f6aed1a463e016
          GIST_ID: 227497e256dba976e8d18e3aab63b265
          TIMEZONE: Asia/Seoul
